[project]
name = "pivpnpy"
version = "0.0.1"
description = "Thin python wrapper for the pivpn command-line tool"
readme = "README.md"
requires-python = ">=3.6"

[project.urls]
Homepage = "https://github.com/m00ninite/pivpnpy"